# Application name
spring:
  application:
    name: generic-integration

  data:
    arangodb:
      host: localhost
      port: 8529
      user: root
#      password: your db password
      database: file_integration

server:
  port: 8080

# Integration configuration
integration:
  inbound-folder: data/inbound
  outbound-folder: data/outbound
  error-folder: data/error
  processed-folder: data/processed
#  kafka-topic: your kafka topic
#  kafka-brokers: your kafka broker
#  s3-bucket: your bucket name like file-base bucket
#  s3-accessKey: your access key related to bucket and server
#  s3-secretKey: your security key related to bucket and server
#  s3-endpoint:  your file-base endpoint like https://s3.filebase.com

# Camel and Kafka configuration
camel:
  springboot:
    name: GenericIntegrationCamel
  component:
    kafka:
#      brokers: your kafka broker
      security-protocol: SASL_SSL
      sasl-mechanism: PLAIN
      sasl-jaas-config: >
        org.apache.kafka.common.security.plain.PlainLoginModule
        required
#        username="Your online kafka server username"
#        password="Your online kafka server password";
      ssl-endpoint-identification-algorithm: https

# Logging levels
logging:
  level:
    com.police: DEBUG
    org.apache.camel: INFO

# Actuator management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


